[version]
path = "src/dbt/adapters/sail/__version__.py"
pattern = "version = \"(?P<version>[^\"]+)\""

[build.targets.wheel]
packages = ["src/dbt"]

[envs.default]
python = "3.12"
dependencies = [
    "dbt-adapters @ git+https://github.com/dbt-labs/dbt-adapters.git#subdirectory=dbt-adapters",
    "dbt-common @ git+https://github.com/dbt-labs/dbt-common.git",
    "dbt-core @ git+https://github.com/dbt-labs/dbt-core.git#subdirectory=core",
    "dbt-tests-adapter @ git+https://github.com/dbt-labs/dbt-adapters.git#subdirectory=dbt-tests-adapter",
    "dbt-spark[session]",
    "pyspark[connect]",
    "pre-commit==3.7.0",
    "pytest>=7.0,<8.0",
    "pytest-xdist",
]

[envs.default.scripts]
setup = [
    "pre-commit install",
]
code-quality = "pre-commit run --all-files"
unit-tests = "python -m pytest {args:tests/unit}"
integration-tests = "python -m pytest {args:tests/functional}"
